In [47]:
#goal is to load an image
import torch
import torchvision
import os
import numpy as np
import matplotlib.pyplot as plt
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torchvision.transforms as transforms
from torchvision.transforms import ToTensor
%matplotlib inline

In [48]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16 * 94 * 94, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84,4)  #age (0 to 1 * 100), gender (<0.5 -> F, >=0.5 -> M), race ((0 to 1) / nraces) 

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 16 * 94 * 94)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

In [49]:
net = Net()
net.load_state_dict(torch.load("pth_files/mse_gender.pth"))

<All keys matched successfully>

In [50]:
import cv2

In [78]:
#quick read of myself

img = cv2.imread("arf.jpeg")
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
print(img.shape)
img = cv2.resize(img, (200,200))
print(img.shape)

(200, 200, 3)
(200, 200, 3)


In [79]:
img

array([[[ 64,  69,  46],
        [ 63,  68,  45],
        [ 62,  67,  44],
        ...,
        [ 76,  84,  63],
        [ 71,  79,  58],
        [ 68,  76,  55]],

       [[ 64,  69,  46],
        [ 63,  68,  45],
        [ 61,  66,  43],
        ...,
        [ 77,  85,  64],
        [ 73,  81,  60],
        [ 69,  77,  56]],

       [[ 64,  70,  44],
        [ 62,  68,  42],
        [ 59,  65,  39],
        ...,
        [ 80,  88,  65],
        [ 74,  82,  61],
        [ 71,  79,  58]],

       ...,

       [[178, 173, 153],
        [177, 172, 152],
        [177, 172, 152],
        ...,
        [174, 173, 152],
        [174, 173, 152],
        [175, 174, 153]],

       [[178, 173, 153],
        [178, 173, 153],
        [177, 172, 152],
        ...,
        [174, 173, 152],
        [174, 173, 152],
        [175, 174, 153]],

       [[179, 174, 154],
        [178, 173, 153],
        [177, 172, 152],
        ...,
        [174, 173, 152],
        [175, 174, 153],
        [176, 175, 154]]

In [80]:
tensor_image = torch.from_numpy(img)

In [82]:
x = torch.reshape(tensor_image, (-1, ))
torch.reshape(x, (-1,3,200,200))

tensor([[[[ 64,  69,  46,  ...,  42,  51,  67],
          [ 40,  47,  63,  ..., 120,  86,  90],
          [120,  86,  88,  ...,  68,  76,  55],
          ...,
          [199, 169, 225,  ..., 110, 110,  84],
          [ 68,  68,  44,  ..., 151, 137, 156],
          [150, 139, 155,  ..., 133, 104, 227]],

         [[188, 157, 222,  ..., 107, 107,  81],
          [ 66,  66,  42,  ..., 154, 140, 157],
          [149, 141, 154,  ...,  79,  47, 221],
          ...,
          [229, 225, 234,  ..., 232, 229, 223],
          [232, 229, 222,  ..., 164, 146, 110],
          [185, 170, 139,  ..., 229, 223, 232]],

         [[229, 224, 233,  ..., 232, 229, 223],
          [232, 229, 222,  ..., 163, 147, 111],
          [181, 168, 134,  ..., 230, 224, 233],
          ...,
          [179, 174, 154,  ...,  80, 170, 123],
          [ 81, 170, 123,  ..., 117,  66, 167],
          [117,  66, 168,  ..., 176, 175, 154]]]], dtype=torch.uint8)

In [95]:
y = x.repeat(4,1)
ti = torch.reshape(y, (4, 3, 200, 200)).float()

In [96]:
prediction = net(ti)

In [97]:
prediction

tensor([[0.5810, 0.5666, 0.6214, 0.5590]], grad_fn=<AddmmBackward>)

In [94]:
prediction.mean()

tensor(0.5820, grad_fn=<MeanBackward0>)